fn solve_q2() -> Result<(), Box<dyn std::error::Error>> {
    Ok(())
}

pub fn main() {
    if let Err(e) = solve_q2() {
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }
}
